cluster:
  name: <cluster.name>
  backup:
    image_url: <cluster.backup.image_url>
  image_list:
    url: <cluster.image_list.url>
    groups:
      - general
  store:
    script_url: <config.store.script_url>
